CC=g++


SOURSE_FILES=main.cpp Strat_Coop.cpp Game_Detailed.cpp Game_Not_Detailed.cpp GameRun.cpp Game_Tournament.cpp InputParser.cpp MatrixReader.cpp Strat_1_Simple.cpp Strat_2_Simple.cpp Strat_3_Simple.cpp Strat_Ever_Score.cpp
OBJECT_FILES=$(SOURSE_FILES:.c=.o)

MAIN=GameRun

all: 
	$(CC) -std=c++11 $(SOURSE_FILES) -o $(MAIN)
