CC=g++


INCLUDES=-I/home/ilia/Proga/15202_sidorov/Lab2_Prisoners/include/

SOURSE_FILES=main.cpp Game_Detailed.cpp Game_Not_Detailed.cpp GameRun.cpp Game_Tournament.cpp InputParser.cpp MatrixReader.cpp Strat_1_Simple.cpp Strat_2_Simple.cpp
OBJECT_FILES=$(SOURSE_FILES:.c=.o)

MAIN=GameRun

all: 
	$(CC) -std=c++11 $(INLCUDES) $(SOURSE_FILES) -o $(MAIN)
