######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 21:15:56 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += feild.h feild_widget.h menu_widget.h Painter.h
SOURCES += feild.cpp feild_widget.cpp main.cpp menu_widget.cpp
