######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 23 10:28:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += feild.h feild_widget.h get_feild.h menu_widget.h Painter.h
SOURCES += feild.cpp feild_widget.cpp get_feild.cpp main.cpp menu_widget.cpp
